sonar.projectKey=stockpro-frontend
sonar.projectName=StockPro Frontend
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,node_modules/**,.angular/**,dist/**
sonar.coverage.exclusions=src/app/features/**,src/app/app.config.ts,src/app/app.routes.ts,src/app/core/models/**

sonar.javascript.lcov.reportPaths=coverage/stockpro-frontend/lcov.info
